// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Album.Data;
using Album.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace Album.Data.Configurations
{
    public partial class ArtistAlbumTracksConfiguration : IEntityTypeConfiguration<ArtistAlbumTracks>
    {
        public void Configure(EntityTypeBuilder<ArtistAlbumTracks> entity)
        {
            entity.HasNoKey();

            entity.ToView("ArtistAlbumTracks");

            entity.Property(e => e.AlbumName)
                .IsRequired()
                .HasMaxLength(160);

            entity.Property(e => e.ArtistName).HasMaxLength(120);

            entity.Property(e => e.TrackName)
                .IsRequired()
                .HasMaxLength(200);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ArtistAlbumTracks> entity);
    }
}
