// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Album.Data.Models
{
    public partial class ArtistAlbumTracks
    {
        public int AlbumId { get; set; }
        public int TrackId { get; set; }
        public int ArtistId { get; set; }
        public string TrackName { get; set; }
        public string AlbumName { get; set; }
        public string ArtistName { get; set; }
    }
}